In [6]:
import pandas as pd

# 1. Lendo o arquivo principal
df_bruto = pd.read_csv('tbEstabelecimento202601.csv', sep=';', low_memory=False, encoding='latin1')

# 2. Mostrando o tamanho com nome de todas as colunas
print(f"Total de linhas no Brasil: {df_bruto.shape[0]}")
print("\n--- COLUNAS DISPONÍVEIS ---")
print(list(df_bruto.columns))

display(df_bruto.head(20))

Total de linhas no Brasil: 602160

--- COLUNAS DISPONÍVEIS ---
['CO_UNIDADE', 'CO_CNES', 'NU_CNPJ_MANTENEDORA', 'TP_PFPJ', 'NIVEL_DEP', 'NO_RAZAO_SOCIAL', 'NO_FANTASIA', 'NO_LOGRADOURO', 'NU_ENDERECO', 'NO_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP', 'CO_REGIAO_SAUDE', 'CO_MICRO_REGIAO', 'CO_DISTRITO_SANITARIO', 'CO_DISTRITO_ADMINISTRATIVO', 'NU_TELEFONE', 'NU_FAX', 'NO_EMAIL', 'NU_CPF', 'NU_CNPJ', 'CO_ATIVIDADE', 'CO_CLIENTELA', 'NU_ALVARA', 'DT_EXPEDICAO', 'TP_ORGAO_EXPEDIDOR', 'DT_VAL_LIC_SANI', 'TP_LIC_SANI', 'TP_UNIDADE', 'CO_TURNO_ATENDIMENTO', 'CO_ESTADO_GESTOR', 'CO_MUNICIPIO_GESTOR', "TO_CHAR(DT_ATUALIZACAO,'DD/MM/YYYY')", 'CO_USUARIO', 'CO_CPFDIRETORCLN', 'REG_DIRETORCLN', 'ST_ADESAO_FILANTROP', 'CO_MOTIVO_DESAB', 'NO_URL', 'NU_LATITUDE', 'NU_LONGITUDE', "TO_CHAR(DT_ATU_GEO,'DD/MM/YYYY')", 'NO_USUARIO_GEO', 'CO_NATUREZA_JUR', 'TP_ESTAB_SEMPRE_ABERTO', 'ST_GERACREDITO_GERENTE_SGIF', 'ST_CONEXAO_INTERNET', 'CO_TIPO_UNIDADE', 'NO_FANTASIA_ABREV', 'TP_GESTAO', "TO_CHAR(DT_ATUALIZACAO_ORIGEM,'DD/MM/YYYY')", 'CO_TIPO_ESTABELECIMENTO', 'CO_ATIVIDADE_PRINCIPAL', 'ST_CONTRATO_FORMALIZADO', 'CO_TIPO_ABRANGENCIA', 'ST_COWORKING']

,CO_UNIDADE,CO_CNES,NU_CNPJ_MANTENEDORA,TP_PFPJ,NIVEL_DEP,NO_RAZAO_SOCIAL,NO_FANTASIA,NO_LOGRADOURO,NU_ENDERECO,NO_COMPLEMENTO,...,ST_CONEXAO_INTERNET,CO_TIPO_UNIDADE,NO_FANTASIA_ABREV,TP_GESTAO,"TO_CHAR(DT_ATUALIZACAO_ORIGEM,'DD/MM/YYYY')",CO_TIPO_ESTABELECIMENTO,CO_ATIVIDADE_PRINCIPAL,ST_CONTRATO_FORMALIZADO,CO_TIPO_ABRANGENCIA,ST_COWORKING
0,2609602569302,2569302,1.040418e+13,3,3,PREFEITURA MUNICIPAL DE OLINDA,USF BULTRINS MONTE II,RUA PREFEITO MANOEL REGUEIRA,540,NaN,...,S,NaN,NaN,M,18/06/2003,NaN,NaN,NaN,NaN,NaN
1,2609602571943,2571943,1.040418e+13,3,3,PREFEITURA MUNICIPAL DE OLINDA,UNIDADE MOVEL,RUA DO SOL,311,NaN,...,N,NaN,NaN,M,18/06/2003,16.0,1.0,NaN,NaN,N
2,2609602344637,2344637,1.040418e+13,3,3,PREFEITURA MUNICIPAL DE OLINDA,USF ALTO DA MINA,RUA AVENCA,49,NaN,...,S,NaN,NaN,M,30/10/2001,1.0,12.0,NaN,NaN,N
3,2609602344696,2344696,1.040418e+13,3,3,PREFEITURA MUNICIPAL DE OLINDA,USF ILHA DE SANTANA I E II,RUA DA INTEGRACAO,S/N,NaN,...,S,NaN,NaN,M,30/10/2001,1.0,12.0,NaN,NaN,N
4,3112002142295,2142295,NaN,3,1,FUNDACAO COMUNITARIA DE SAUDE DE CANDEIAS,HOSPITAL CARLOS CHAGAS,AVENIDA PEDRO VIEIRA DE AZEVEDO,687,NaN,...,S,NaN,NaN,M,21/03/2002,6.0,9.0,S,NaN,N
5,3112602121506,2121506,NaN,3,1,LABORATORIO CENTRAL DE CAPINOPOLIS LTDA,LABORATORIO CENTRAL,AV 99,613,NaN,...,NaN,NaN,NaN,D,12/03/2002,NaN,NaN,NaN,NaN,NaN
6,3112902759861,2759861,NaN,3,1,LABORATORIO SANTA HELENA LTDA,LABORATORIO SANTA HELENA,AV MANOEL FRANCISCO DE FREITAS,57,NaN,...,S,NaN,NaN,M,12/09/2003,18.0,2.0,NaN,NaN,N
7,2917702533324,2533324,1.398832e+13,3,3,MUNICIPIO DE JAGUARARI,POSTO DE SAUDE DE ABOBORA,POVOADO DE ABOBORA,S/N,TERREO,...,NaN,NaN,NaN,M,25/07/2003,NaN,NaN,NaN,NaN,NaN
8,2923604029542,4029542,1.367549e+13,3,3,MUNICIPIO DE PARAMIRIM,UNIDADE DO PSF DE CANABRAVINHA,DISTRITO DE CANABRAVINHA,S/N,NaN,...,S,NaN,NaN,M,20/02/2004,1.0,12.0,NaN,3.0,N
9,4218506433839,6433839,NaN,1,1,CONSULTORIO ODONTOLOGICO JOAO R MARANHA,CONSULTORIO ODONTOLOGICO JOAO R MARANHA,RUA JOSE BONIFACIO,10,1 ANDAR SALA 11,...,S,NaN,NaN,M,16/02/2010,14.0,26.0,NaN,NaN,N
10,4204502300125,2300125,NaN,3,1,SINDICATO DOS TRABALHADORES RURAIS DE CORUPA,STR DE CORUPA,AVN GETULIO VARGAS,611,NaN,...,S,NaN,NaN,M,30/10/2001,NaN,NaN,NaN,NaN,NaN
11,5300103107981,3107981,NaN,1,1,ROMEU ARAKAKI,ROMEU ARAKAKI,SEPS EQ 705 905 CONJUNTO B SALA,325,NaN,...,NaN,NaN,NaN,E,03/07/2004,NaN,NaN,NaN,NaN,NaN
12,4204502662922,2662922,8.310247e+13,3,3,PREFEITURA MUNICIPAL DE CORUPA,EQUIPE MULTIDISCIPLINAR CORUPA,RUA VIDAL RAMOS,82,NaN,...,S,NaN,NaN,M,17/03/2003,1.0,12.0,S,3.0,N
13,4304605396786,5396786,NaN,1,1,CHARLES AUGUSTO RUBENICH DE FREITAS,CHARLES AUGUSTO RUBENICH DE FREITAS,RUA QUINZE DE JANEIRO,231,305,...,N,NaN,NaN,M,06/10/2009,16.0,1.0,NaN,NaN,N
14,2408102680041,2680041,NaN,3,1,LABORATORIO DE ANATOMIA PATOLOGICA E CITOPATOL...,LABORATORIO DE ANATOMIA PATOLOGICA E CITOPATOL...,RUA TUIUTI,264,NaN,...,S,NaN,NaN,M,05/08/2003,18.0,2.0,S,NaN,N
15,1100122495724,2495724,4.092672e+12,3,3,PREFEITURA MUNICIPAL DE JIPARANA,PS SANTO ANTONIO JIPARANA,LINHA SANTA RITA,S/N,PROJETO RIACHUELO,...,NaN,NaN,NaN,M,30/01/2002,NaN,NaN,NaN,NaN,NaN
16,3201302445107,2445107,2.715055e+13,3,3,PREFEITURA MUNICIPAL DE CARIACICA,US ALTO LAGE,EDMILSON VAREJAO,104,NaN,...,S,NaN,NaN,M,17/12/2003,1.0,12.0,NaN,3.0,N
17,3201302445131,2445131,2.715055e+13,3,3,PREFEITURA MUNICIPAL DE CARIACICA,US BELA VISTA,AVENIDA AYMORES,S/N,NaN,...,S,NaN,NaN,M,17/12/2003,1.0,12.0,NaN,3.0,N
18,3201302445166,2445166,2.715055e+13,3,3,PREFEITURA MUNICIPAL DE CARIACICA,US JOAQUIM LOVATI SANTA FE,RUA PADRE PIO,S/N,NaN,...,S,NaN,NaN,M,17/12/2003,1.0,12.0,NaN,3.0,N
19,3155302108887,2108887,1.836398e+13,3,3,PREFEITURA MUNICIPAL DE RIO MANSO,RIO MANSO POSTO DE SAUDE MUNICIPAL JOSE BATIST...,RUA BONFIM,422,NaN,...,S,NaN,NaN,M,25/07/2003,1.0,12.0,NaN,3.0,N

In [16]:
import pandas as pd
import numpy as np

print("\n--- Parte 1: Carregando a base nacional... ---")
df_bruto = pd.read_csv('tbEstabelecimento202601.csv', sep=';', low_memory=False, encoding='latin1')

print("Filtrando os estabelecimentos do Rio Grande do Norte (IBGE 24)...")
df_rn = df_bruto[df_bruto['CO_MUNICIPIO_GESTOR'].astype(str).str.startswith('24')].copy()

colunas_interesse = [
    'TP_UNIDADE', 'CO_NATUREZA_JUR', 'TP_GESTAO', 'CO_TURNO_ATENDIMENTO',
    'CO_ATIVIDADE_PRINCIPAL', 'TP_ESTAB_SEMPRE_ABERTO', 'ST_CONEXAO_INTERNET',
    'CO_CLIENTELA', 'NU_LATITUDE', 'NU_LONGITUDE'
]

df = df_rn[colunas_interesse].copy()

# 1. Substitui a vírgula por ponto (mas ainda é texto)
df['NU_LATITUDE'] = df['NU_LATITUDE'].astype(str).str.replace(',', '.')
df['NU_LONGITUDE'] = df['NU_LONGITUDE'].astype(str).str.replace(',', '.')

# 2. Força a conversão para número. O que for texto ('undefined') vira NaN (Not a Number / Vazio)
df['NU_LATITUDE'] = pd.to_numeric(df['NU_LATITUDE'], errors='coerce')
df['NU_LONGITUDE'] = pd.to_numeric(df['NU_LONGITUDE'], errors='coerce')

print(f"\nTotal de {df.shape[0]} estabelecimentos de saúde separados para análise.")
display(df.head())

--- Parte 1: Carregando a base nacional... ---
Filtrando os estabelecimentos do Rio Grande do Norte (IBGE 24)...

Total de 7448 estabelecimentos de saúde separados para análise.

,TP_UNIDADE,CO_NATUREZA_JUR,TP_GESTAO,CO_TURNO_ATENDIMENTO,CO_ATIVIDADE_PRINCIPAL,TP_ESTAB_SEMPRE_ABERTO,ST_CONEXAO_INTERNET,CO_CLIENTELA,NU_LATITUDE,NU_LONGITUDE
14,39,2062.0,M,3.0,2.0,N,S,3.0,-5.786853,-35.195943
269,1,1244.0,M,3.0,12.0,N,N,1.0,-4.956152,-37.136922
270,2,1244.0,M,3.0,12.0,N,N,3.0,-4.951342,-37.131064
271,2,1244.0,M,3.0,12.0,N,S,3.0,-6.170000,-35.240000
272,2,1244.0,M,3.0,12.0,N,S,3.0,-6.194000,-35.140000

In [17]:
print('\n--- Parte 2: Limpeza e tratamento dos dados ---')

#Separando coordenadas e textos:
colunas_numericas = ['NU_LATITUDE', 'NU_LONGITUDE']
colunas_texto = [col for col in df.columns if col not in colunas_numericas]

#Removendo coordenadas vazias, que são insignificantes:
tamanho_antes = df.shape[0]
df = df.dropna(subset=colunas_numericas)
print(f"\nPostos de saúde sem coordenadas removidas: {tamanho_antes - df.shape[0]}")

#Corrigindo valores de texto que estão em branco com Moda:
for col in colunas_texto:
    df[col] = df[col].fillna(df[col].mode()[0])

print(f"Total de postos aptos para análise: {df.shape[0]}")

#Transformando categórico em numéricos (Estou preferindo utilizar One Hot Encoding neste caso):
df_encoded = pd.get_dummies(df, columns=colunas_texto, dtype=int)

print(f"\nO One-Hot Encoding transformou nossas {df.shape[1]} colunas originais em {df_encoded.shape[1]} colunas!")
display(df_encoded.head())

--- Parte 2: Limpeza e tratamento dos dados ---

Postos de saúde sem coordenadas removidas: 526
Total de postos aptos para análise: 6922

O One-Hot Encoding transformou nossas 10 colunas originais em 109 colunas!

,NU_LATITUDE,NU_LONGITUDE,TP_UNIDADE_1,TP_UNIDADE_2,TP_UNIDADE_4,TP_UNIDADE_5,TP_UNIDADE_7,TP_UNIDADE_15,TP_UNIDADE_16,TP_UNIDADE_20,...,CO_ATIVIDADE_PRINCIPAL_24.0,CO_ATIVIDADE_PRINCIPAL_26.0,CO_ATIVIDADE_PRINCIPAL_27.0,TP_ESTAB_SEMPRE_ABERTO_N,TP_ESTAB_SEMPRE_ABERTO_S,ST_CONEXAO_INTERNET_N,ST_CONEXAO_INTERNET_S,CO_CLIENTELA_1.0,CO_CLIENTELA_2.0,CO_CLIENTELA_3.0
14,-5.786853,-35.195943,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
269,-4.956152,-37.136922,1,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
270,-4.951342,-37.131064,0,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,1
271,-6.170000,-35.240000,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
272,-6.194000,-35.140000,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1

In [19]:
from sklearn.preprocessing import StandardScaler

print('\n--- Parte 3: Remoção de outliers, normalização e exportação ---')

#Suavização de outliers com IQR:
colunas_continuas = ['NU_LATITUDE', 'NU_LONGITUDE']

for col in colunas_continuas:
    Q1 = df_encoded[col].quantile(0.25)
    Q3 = df_encoded[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    df_encoded = df_encoded[(df_encoded[col] >= limite_inferior) & (df_encoded[col] <= limite_superior)]

print(f"\nTamanho da base após filtro de outliers nas coordenadas: {df_encoded.shape[0]} postos.")

#Colocando na mesma escala com Normalização:
scaler = StandardScaler()
dados_escalados = scaler.fit_transform(df_encoded)

df_final = pd.DataFrame(dados_escalados, columns=df_encoded.columns)

#Salvando a base alterada para comparação final:
df_final.to_csv('base_sus_rn_tratada.csv', index=False)

print("\nFASE 1 FINALIZADA")
print("\nArquivo 'base_sus_rn_tratada.csv' salvo.")
display(df_final.head())

--- Parte 3: Remoção de outliers, normalização e exportação ---

Tamanho da base após filtro de outliers nas coordenadas: 5639 postos.

FASE 1 FINALIZADA

Arquivo 'base_sus_rn_tratada.csv' salvo.

,NU_LATITUDE,NU_LONGITUDE,TP_UNIDADE_1,TP_UNIDADE_2,TP_UNIDADE_4,TP_UNIDADE_5,TP_UNIDADE_7,TP_UNIDADE_15,TP_UNIDADE_16,TP_UNIDADE_20,...,CO_ATIVIDADE_PRINCIPAL_24.0,CO_ATIVIDADE_PRINCIPAL_26.0,CO_ATIVIDADE_PRINCIPAL_27.0,TP_ESTAB_SEMPRE_ABERTO_N,TP_ESTAB_SEMPRE_ABERTO_S,ST_CONEXAO_INTERNET_N,ST_CONEXAO_INTERNET_S,CO_CLIENTELA_1.0,CO_CLIENTELA_2.0,CO_CLIENTELA_3.0
0,0.552728,0.652505,-0.216285,-0.425955,-0.114522,-0.132298,-0.054989,-0.092656,-0.02979,-0.026643,...,-0.04807,-0.042149,-0.062583,0.266524,-0.266524,-0.319395,0.319395,-0.945616,-0.216734,1.034465
1,-0.991817,0.604632,-0.216285,2.347668,-0.114522,-0.132298,-0.054989,-0.092656,-0.02979,-0.026643,...,-0.04807,-0.042149,-0.062583,0.266524,-0.266524,-0.319395,0.319395,-0.945616,-0.216734,1.034465
2,-1.088566,0.713293,-0.216285,2.347668,-0.114522,-0.132298,-0.054989,-0.092656,-0.02979,-0.026643,...,-0.04807,-0.042149,-0.062583,0.266524,-0.266524,-0.319395,0.319395,-0.945616,-0.216734,1.034465
3,-0.676089,0.431596,4.623525,-0.425955,-0.114522,-0.132298,-0.054989,-0.092656,-0.02979,-0.026643,...,-0.04807,-0.042149,-0.062583,0.266524,-0.266524,-0.319395,0.319395,-0.945616,-0.216734,1.034465
4,0.588569,0.594680,-0.216285,-0.425955,-0.114522,-0.132298,-0.054989,-0.092656,-0.02979,-0.026643,...,-0.04807,-0.042149,-0.062583,0.266524,-0.266524,-0.319395,0.319395,1.057512,-0.216734,-0.966683

In [20]:
print('\n--- Parte 3.2: Criando base alternativa com Frequency Encoding ---')

df_frequencia = df.copy()

#Aplicação do Frequency Encoding nas colunas de texto:
for col in colunas_texto:
    frequencia = df_frequencia[col].value_counts(normalize=True)
    df_frequencia[col] = df_frequencia[col].map(frequencia)

print(f"\nForam mantidas as {df_frequencia.shape[1]} colunas originais")
display(df_frequencia.head())

#Suavização de outliers com IQR:
for col in colunas_numericas:
    Q1 = df_frequencia[col].quantile(0.25)
    Q3 = df_frequencia[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    df_frequencia = df_frequencia[(df_frequencia[col] >= limite_inferior) & (df_frequencia[col] <= limite_superior)]

#Aplicando normalização:
scaler_freq = StandardScaler()
dados_escalados_freq = scaler_freq.fit_transform(df_frequencia)
df_final_frequencia = pd.DataFrame(dados_escalados_freq, columns=df_frequencia.columns)

#Exportando segunda versão com frequency encoding:
df_final_frequencia.to_csv('base_sus_rn_frequencia.csv', index=False)
print("\nBase com frequency encoding salva com sucesso")

--- Parte 3.2: Criando base alternativa com Frequency Encoding ---

Foram mantidas as 10 colunas originais

,TP_UNIDADE,CO_NATUREZA_JUR,TP_GESTAO,CO_TURNO_ATENDIMENTO,CO_ATIVIDADE_PRINCIPAL,TP_ESTAB_SEMPRE_ABERTO,ST_CONEXAO_INTERNET,CO_CLIENTELA,NU_LATITUDE,NU_LONGITUDE
14,0.069055,0.334008,0.978619,0.803669,0.082202,0.931523,0.904363,0.445825,-5.786853,-35.195943
269,0.045940,0.336319,0.978619,0.803669,0.185207,0.931523,0.095637,0.510979,-4.956152,-37.136922
270,0.157469,0.336319,0.978619,0.803669,0.185207,0.931523,0.095637,0.445825,-4.951342,-37.131064
271,0.157469,0.336319,0.978619,0.803669,0.185207,0.931523,0.904363,0.445825,-6.170000,-35.240000
272,0.157469,0.336319,0.978619,0.803669,0.185207,0.931523,0.904363,0.445825,-6.194000,-35.140000

Base com frequency encoding salva com sucesso